# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:pJ2VXQ==,iv:4WhZ1l7gPWH8RHSFGLd9xhYJav+CRyahpGh5PhmTPuI=,tag:EBKvsPgWaAPOY0E6nOgFuQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:8gJP0dC0xVcqGVNuhbS0HWz9GeyF90e0MzHdNqaxjiltAfsGGlSloCF5x3r7cUbaPZkfFoQp5mLp+uJpGcNzeMONdWfaA4GTYuk8,iv:P/JvMQRhPc0uMhr0jnZC0R8OxMpNpXDsrpq+V37x0CQ=,tag:LofOQmloBYs5Xz3RvR3b3A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h0fw2w4kjd2ah8ff03hut53wa6s7x2cvt0jqppegm6nt6ppjgawqvz63ev
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZm9WamxTZjNHM01xL01D
        NjdCaU5BN2RaWk9YZUJNcVBjQmljaGZXWUJNCnRqaVNxM1I0elo2ZjZRU3ZJTnhU
        YWJyVG8xbGowRUFyZFJzR2dGSy8vSFUKLS0tIFYycEMrV0w0bDJMOGwwWlJJR1ZE
        UVpnLzd0aWV0V1NHZ0hyZWVyYmpOZm8K+hhrii+VpaVbi5g8f5ST6dJrnLU2xvR1
        /NwUR56NhrS4/+EKMd1sNDioePF02Y7EogECpr18T1GYNoTp3MrIsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-14T17:48:39Z"
  mac: ENC[AES256_GCM,data:UonpUbr+ZA9gA4uBP+f6n9KGw5Kz3+xi4oRBOlvXzBMkyEA7wG8PIUn+7W8Z/xvEmxnBjk8MgeppFkm/RdeEWSDqRGU3qjMUGqMJHeMvzzy6XC7SS1FcnmQD2Or6cJeeIXDHyd0/H9oDOW7SDV+P/OI9BCUt0p5SWS7dvRXvDjY=,iv:+sEBP6PIZ+3O+EkLlYsLfR2tM1ZEiQJtG0zXxgBMIfQ=,tag:2bwMqa4OsBd/NexFwntkuQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
