# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:j2sbwheA8Jnt,iv:Ph9onNwwxz2jlhrEEepPRTNzDvsyyf41j1fNzl3BSAs=,tag:CmrRFCXpE9UzBDEx3TGXcw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h0fw2w4kjd2ah8ff03hut53wa6s7x2cvt0jqppegm6nt6ppjgawqvz63ev
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNklvMnFrVk9UTXJCVVJm
        MklxZjdFZ1RKdmo3WEwwc0tOeHJXeGc4UDE4ClphVXZ1RHprdENCRWJuc1pXRldm
        OTFrajlYcVZweVo0RHhLMzlWbUJzZmMKLS0tIEVFenNNU3g2SUMvOGgyTUVVYmxq
        b0Z0NTVENFI0VXhRSGV3U1NOSnJqZTgKUsYcRVAs7op4fjzGfsHA8w7H5gJe1Fg3
        5D0Mn4GMBrXWZtoDVTMbBWQ6sAkoz10IkO7/duAk9p+v0pNB0po45w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-14T17:48:39Z"
  mac: ENC[AES256_GCM,data:4rUJ8ynIgjBKiGqcLbhUVR9t+cjd7ZxUq0FCQJ2+SS8JEppzCsRN3Z5EoO86+kgbCH+ds+1VfWGMwhHRD4en9W9qlQw21yylgEvKS/kZbUITo7LIRgaawRYyxJ9WvFiWGQnMGHZuvBzVULjJov5r99fF16jvWnnzeXokP+DRAUw=,iv:9htMGUImXM1zQ/KE91m0mEzecXAEphMpyB3/9jqYVkM=,tag:Q0AetHu+Oh71+UjyQXrNUQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
