apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Hzsh/xwFqDyctR9V,iv:caIUSe4McR2vBhDb5M74qt9O0LCl7cIqiN0CmLYoO2c=,tag:ay7IOBhst80/Ug03Tt4J/A==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:jsNW2g==,iv:9noHp+zotTwfufloKLpaNcdDSMD9ux0wGFHetpRp5No=,tag:m8tap9/O4ke7TkkTAxlRQg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h0fw2w4kjd2ah8ff03hut53wa6s7x2cvt0jqppegm6nt6ppjgawqvz63ev
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MzNNYmVEa1FxNUxGdFVL
        NHpyakZnd05FM0ppVHZ1TjZSS09SSDVnN2k4CnZrT1JzNkdCL1ZTclVDcHBxSUxE
        L3N4djlLWFhVM2lkL1MxYytjVFk3K00KLS0tIFB3VkdncElXRlJHdTJXdUgxblJF
        R3lsWS90MnBaWEh2SkxHek8zN1pxelkKSBsjMgX+KG+s3Rz6n9VoaNj5zljlGx0V
        /mhnBI4GB+t7PXD9dIswY5jQGvRCMHjg68R5SEBB1g7ss6PntWzYcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-14T17:48:39Z"
  mac: ENC[AES256_GCM,data:B0Krqb8ctmmD7DeAf0rJikuDWciBwbpaRrDwyaQbjxi0nvaCP25W/NYdbzD5+U1Xp59rhqH3F7TpVA+cMzEesEV2juRixutfBUgTME0AZQiNtqr6axkHuv3Zm8jsZwcVd7GredXh+v6LlsUaij2PxA8fUW4u26eWGG1ZbADCpUQ=,iv:KGk1Ub1YMV/nZgJfU7ts/YXkvdLn/CvdYIQHg5LSoFU=,tag:WVY4O/sArOD0Gul4tkskMw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
